apiVersion: v1
kind: Service
metadata:
  name: nodeport
spec:
  type: NodePort
  selector:
    # this selector must match label of pod
    type: pod
  ports:
    - name: http
      port: 80
      targetPort: 80
      # range from 30000-32767
      nodePort: 31300
