apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: new-rc
  labels:
    type: rc
spec:
  template:
    metadata:
      name: pod
      labels:
        type: pod
    spec:
      containers:
        - name: nginx-controller
          image: nginx
  replicas: 4
  selector:
    matchLabels:
      type: pod
