apiVersion: v1
kind: ReplicationController
metadata:
  name: rc
  labels:
    type: rc
spec:
  template:
    metadata:
      name: pod
      labels:
        type: pod
    spec:
      containers:
        - name: nginx-controller
          image: nginx
  replicas: 4
