apiVersion: v1
kind: Secret
metadata:
  name: secret
# https://kubernetes.io/docs/concepts/configuration/secret 
type: Opaque
data:
  # Note: The values must be base64-encoded
  # echo -n 'password' | base64
  username: dXNlcm5hbWU= # "username" base64 encoded
  password: cGFzc3dvcmQ= # "password" base64 encoded
